
export const SELECT_DELIVERY_ITEM = 'SELECT_DELIVERY_ITEM'
export const NEW_SHIPMENT = 'NEW_SHIPMENT'
export const UPDATE_PARCEL_PACKAGE_COUNT = 'UPDATE_PARCEL_PACKAGE_COUNT'
export const CONFIRM_SHIPMENT = 'CONFIRM_SHIPMENT'
export const REMOVE_SELECTED_ITEM = 'REMOVE_SELECTED_ITEM'
export const ADDRESS_INPUT_CHANGE = 'ADDRESS_INPUT_CHANGE'